name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
      - uses: borales/actions-yarn@v4
        name: lint the files
        with:
          cmd: lintCi
      - uses: borales/actions-yarn@v4
        name: build the files
        with:
          cmd: build
      - uses: borales/actions-yarn@v4
        name: Run unit tests with jest
        with:
          cmd: test
      - name: Check if dist output is up to date with sources files
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
